table 'Aging Bands'
	lineageTag: 878f7f22-ff42-4b28-9dd1-ece658a152eb

	column Band
		dataType: string
		lineageTag: 3fbdee4c-cfd6-40ef-bdb9-80062449a120
		summarizeBy: none
		sourceColumn: Band
		sortByColumn: SortOrder

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column SortOrder
		dataType: int64
		formatString: 0
		lineageTag: 7d7fc668-2e57-45ed-bbc6-b775bdf9aa17
		summarizeBy: sum
		sourceColumn: SortOrder

		annotation SummarizationSetBy = Automatic

	partition 'Aging Bands' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMtA1V0hJrCxW0lEyVIrViVay0DU2gIkYgUWMDXXN4ELGYCEzQ11LuJAJWCim1MDAOBUhaqoUGwsA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Band = _t, SortOrder = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Band", type text}, {"SortOrder", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

