table dq_pk_null_summary
	lineageTag: bb85591d-9a9b-4279-9c96-8a838c26e40b
	sourceLineageTag: [validate].[dq_pk_null_summary]

	measure 'PK Null Status' =
			
			IF (
			    SUM('dq_pk_null_summary'[null_key_count]) > 0,
			    "Fail",
			    "Pass"
			)
		lineageTag: dff9f41f-38df-4847-b94f-1e6815e0843a

		changedProperty = Name

	column check_type
		dataType: string
		lineageTag: f80c6099-97dd-4603-ad1d-36e0d7a6ec05
		sourceLineageTag: check_type
		summarizeBy: none
		sourceColumn: check_type

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: aa74dc44-8178-4545-b4f1-14d570fb7021
		sourceLineageTag: status
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column table_name
		dataType: string
		lineageTag: 124694c0-4a5b-44c6-9293-91fc90afcbe9
		sourceLineageTag: table_name
		summarizeBy: none
		sourceColumn: table_name

		annotation SummarizationSetBy = Automatic

	column key_column
		dataType: string
		lineageTag: 0c5b6cb7-19fb-4b7b-9fdf-82d4cdf8a5d6
		sourceLineageTag: key_column
		summarizeBy: none
		sourceColumn: key_column

		annotation SummarizationSetBy = Automatic

	column null_key_count
		dataType: int64
		formatString: 0
		lineageTag: 9d11979a-25c1-4843-a907-8fb26739961c
		sourceLineageTag: null_key_count
		summarizeBy: sum
		sourceColumn: null_key_count

		annotation SummarizationSetBy = Automatic

	partition dq_pk_null_summary = entity
		mode: directLake
		source
			entityName: dq_pk_null_summary
			schemaName: validate
			expressionSource: 'DirectLake - Rookie2Engineer_Lakehouse'

